/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtcRouteImport } from './routes/atc'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MyFlightsRouteImport } from './routes/my-flights'
import { Route as ApiPublicPushFlightEventsRouteImport } from './routes/api/public/push/flight-events'
import { Route as ApiPublicAuthDiscordCallbackRouteImport } from './routes/api/public/auth/discord/callback'
import { Route as ApiPublicAuthDiscordStartRouteImport } from './routes/api/public/auth/discord/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtcRoute = AtcRouteImport.update({
  id: '/atc',
  path: '/atc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFlightsRoute = MyFlightsRouteImport.update({
  id: '/my-flights',
  path: '/my-flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushFlightEventsRoute =
  ApiPublicPushFlightEventsRouteImport.update({
    id: '/api/public/push/flight-events',
    path: '/api/public/push/flight-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordCallbackRoute =
  ApiPublicAuthDiscordCallbackRouteImport.update({
    id: '/api/public/auth/discord/callback',
    path: '/api/public/auth/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordStartRoute =
  ApiPublicAuthDiscordStartRouteImport.update({
    id: '/api/public/auth/discord/start',
    path: '/api/public/auth/discord/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atc': typeof AtcRoute
  '/auth': typeof AuthRoute
  '/my-flights': typeof MyFlightsRoute
  '/api/public/push/flight-events': typeof ApiPublicPushFlightEventsRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atc': typeof AtcRoute
  '/auth': typeof AuthRoute
  '/my-flights': typeof MyFlightsRoute
  '/api/public/push/flight-events': typeof ApiPublicPushFlightEventsRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atc': typeof AtcRoute
  '/auth': typeof AuthRoute
  '/my-flights': typeof MyFlightsRoute
  '/api/public/push/flight-events': typeof ApiPublicPushFlightEventsRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atc'
    | '/auth'
    | '/my-flights'
    | '/api/public/push/flight-events'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atc'
    | '/auth'
    | '/my-flights'
    | '/api/public/push/flight-events'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
  id:
    | '__root__'
    | '/'
    | '/atc'
    | '/auth'
    | '/my-flights'
    | '/api/public/push/flight-events'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtcRoute: typeof AtcRoute
  AuthRoute: typeof AuthRoute
  MyFlightsRoute: typeof MyFlightsRoute
  ApiPublicPushFlightEventsRoute: typeof ApiPublicPushFlightEventsRoute
  ApiPublicAuthDiscordCallbackRoute: typeof ApiPublicAuthDiscordCallbackRoute
  ApiPublicAuthDiscordStartRoute: typeof ApiPublicAuthDiscordStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atc': {
      id: '/atc'
      path: '/atc'
      fullPath: '/atc'
      preLoaderRoute: typeof AtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-flights': {
      id: '/my-flights'
      path: '/my-flights'
      fullPath: '/my-flights'
      preLoaderRoute: typeof MyFlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/flight-events': {
      id: '/api/public/push/flight-events'
      path: '/api/public/push/flight-events'
      fullPath: '/api/public/push/flight-events'
      preLoaderRoute: typeof ApiPublicPushFlightEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/callback': {
      id: '/api/public/auth/discord/callback'
      path: '/api/public/auth/discord/callback'
      fullPath: '/api/public/auth/discord/callback'
      preLoaderRoute: typeof ApiPublicAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/start': {
      id: '/api/public/auth/discord/start'
      path: '/api/public/auth/discord/start'
      fullPath: '/api/public/auth/discord/start'
      preLoaderRoute: typeof ApiPublicAuthDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtcRoute: AtcRoute,
  AuthRoute: AuthRoute,
  MyFlightsRoute: MyFlightsRoute,
  ApiPublicPushFlightEventsRoute: ApiPublicPushFlightEventsRoute,
  ApiPublicAuthDiscordCallbackRoute: ApiPublicAuthDiscordCallbackRoute,
  ApiPublicAuthDiscordStartRoute: ApiPublicAuthDiscordStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
